import type { UpgradeCategory } from '@fh6/shared';

/**
 * The physics + reason behind each upgrade category.
 *
 * This is the default "why" shown for any part whose own `rationale` is unset —
 * so every upgrade is explained in the UI, whether it was hand-authored in the
 * seed or generated by the importer (e.g. the ~130 real engine swaps). Parts
 * whose physics differ from their category (turbo vs supercharger, each tire
 * compound, each drivetrain swap) override this with their own `rationale`.
 */
export const CATEGORY_PHYSICS: Record<UpgradeCategory, string> = {
  engine_swap:
    'Swaps in a different engine — the single biggest power change available. Adds (or removes) weight and can shift the car’s balance, so it only suits cars the game allows it on.',
  drivetrain_swap:
    'Changes which wheels are driven, reshaping how the car puts power down and handles. AWD adds traction and launch at a weight cost; RWD/FWD change the balance and shed driveline weight.',
  aspiration:
    'Changes how the engine is fed air (naturally aspirated vs forced induction), the biggest lever on how much power it can make.',
  intake:
    'A freer-flowing intake feeds the engine more air, adding power across the rev range — more at higher tiers.',
  fuel_system:
    'More fuel delivery matches the extra air from other upgrades, letting the engine safely make more power.',
  ignition:
    'A stronger, better-timed spark burns the mixture more completely for a small, reliable power gain.',
  exhaust:
    'A less restrictive exhaust lets spent gases escape faster, freeing up power — especially high in the rev range.',
  camshaft:
    'More aggressive cam profiles hold the valves open further and longer, boosting top-end power for a little low-rpm smoothness.',
  valves:
    'Bigger, lighter valves and stiffer springs improve breathing at high rpm, adding power up top.',
  displacement:
    'Boring/stroking the engine increases its size — more displacement makes more torque and power everywhere.',
  pistons_compression:
    'Lighter forged pistons and higher compression raise power and let the engine rev harder and more safely.',
  intercooler:
    'Cools the intake charge on forced-induction engines — denser air means more power and less knock. Little effect without a turbo or supercharger.',
  oil_cooling:
    'Better oil and cooling keep the engine in its safe window under sustained load; a small, reliability-driven power gain.',
  flywheel:
    'A lighter flywheel lets the engine spin up faster, sharpening throttle response and launch, and sheds a little rotating weight.',
  forced_induction:
    'Forces more air into the engine for a large power increase — the biggest gain short of an engine swap, at some added weight (and, for turbos, throttle lag).',
  brakes:
    'Bigger brakes and better pads increase stopping force and resist fade, so you can brake later and more consistently. Race brakes also unlock brake-bias tuning.',
  springs_dampers:
    'Adjustable coilovers control body roll, pitch and how the tires follow the road — the foundation of handling — and unlock ride-height, spring and damping tuning.',
  front_arb:
    'An adjustable front anti-roll bar tunes how much the front axle resists roll — a primary tool for dialing understeer vs oversteer. Its value is the balance tuning it unlocks.',
  rear_arb:
    'An adjustable rear anti-roll bar tunes how much the rear axle resists roll — stiffer rear means more rotation. Its value is the balance tuning it unlocks.',
  chassis_reinforcement:
    'Stiffening the chassis (or fitting a roll cage) lets the car flex less, so the suspension and alignment work as intended — sharper, more consistent handling for a little added weight.',
  weight_reduction:
    'Removing weight improves everything at once — acceleration, braking, cornering and agility. Higher tiers strip more.',
  clutch:
    'A stronger, lighter clutch shifts faster and puts power down more crisply, improving acceleration and launch.',
  transmission:
    'A better gearbox shifts faster; the race unit is fully tunable, letting you match gear ratios and final drive to the track for stronger acceleration or a higher top speed.',
  driveline:
    'A lighter, stronger driveline loses less power between the engine and the wheels, marginally improving acceleration.',
  differential:
    'A tunable limited-slip differential controls how power splits between the driven wheels — the key to putting power down on corner exit (and to holding a drift). Its value is the traction its tuning unlocks.',
  tire_compound:
    'The tire compound sets how much grip the tires make and on what surface — the single biggest handling choice.',
  front_tire_width:
    'Wider front tires put more rubber on the road for sharper turn-in and front grip, at a little extra weight.',
  rear_tire_width:
    'Wider rear tires improve power-down and traction (and, on RWD, stability), at a little extra weight.',
  rim_style:
    'Lightweight rims cut unsprung weight, so the suspension reacts faster and the car accelerates, brakes and turns slightly better.',
  rim_size:
    'Larger-diameter rims allow wider, lower-profile tires for a touch more grip and response, at a little extra weight.',
  front_aero:
    'An adjustable front splitter adds front downforce, pressing the front tires down for sharper high-speed turn-in — at the cost of a little drag. Unlocks aero tuning.',
  rear_aero:
    'An adjustable rear wing adds rear downforce for high-speed stability and cornering grip, at the cost of some top speed. Unlocks aero tuning.',
};
