// AUTO-GENERATED by scripts/import-game-database.mjs — do not edit.
import gameData from './game-database.json';
import type { CarInput, CarUpgradeProfileInput, PartInput, TuneRangesInput } from '../types.ts';

export const gameCars = gameData.gameCars as CarInput[];
export const gameParts = gameData.gameParts as PartInput[];
export const gameUpgradeProfiles = gameData.gameUpgradeProfiles as CarUpgradeProfileInput[];
export const gameTuneRanges = gameData.gameTuneRanges as TuneRangesInput[];
export const gameEngines = gameData.gameEngines;
export const gameMotors = gameData.gameMotors;
export const gamePhysicsSettings = gameData.gamePhysicsSettings;
export const gameEngineUpgradeSpecs = gameData.gameEngineUpgradeSpecs;
export const gameDatabaseBuild = gameData.gameDatabaseBuild;
